project_id = "wbptvnuyhgstaaufzysh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
[functions.generate-meeting-minutes]
verify_jwt = false

[functions.allowed_http_hosts]
hosts = ["api.openai.com"]