// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbptvnuyhgstaaufzysh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicHR2bnV5aGdzdGFhdWZ6eXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MjQyNTEsImV4cCI6MjA1MDIwMDI1MX0.-wzEsrbHLbcbfe3xdMixrbCH-KVtcf0TOnrwyWK6paA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);